# 生产环境
spring:
  datasource:
    username: root
    password: 123
    # 进入时区报错了，就增加一个时区的配置就ok了，serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/strategic?useUnicode==true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

#logging:
#  level:
#    root: warn
#    com.cola: info
#  file:
#    name: log/blog-por.log

server:
  port: 8081